#define yyFlexLexer Exa1FlexLexer

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
class istream;
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        *yy_cp = yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;

#include <iostream>

using std::istream;
using std::ostream;
using std::cin;
using std::cout;
using std::cerr;
struct yy_buffer_state
    {
    istream* yy_input_file;

    char *yy_ch_buf;		/* input buffer */
    char *yy_buf_pos;		/* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    yy_size_t yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2
    };


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
    { \
    if ( ! yy_current_buffer ) \
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
    yy_current_buffer->yy_is_interactive = is_interactive; \
    }

#define yy_set_bol(at_bol) \
    { \
    if ( ! yy_current_buffer ) \
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
    yy_current_buffer->yy_at_bol = at_bol; \
    }

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include "FlexLexer.h"


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    yytext_ptr = yy_bp; \
    yyleng = (int) (yy_cp - yy_bp); \
    yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
static yyconst short int yy_acclist[472] =
    {   0,
       87,   85,   86,   84,   85,   86,   80,   86,   17,   85,
       86,   85,   86,   37,   85,   86,    5,   85,   86,   18,
       85,   86,   85,   86,   38,   85,   86,   39,   85,   86,
        3,   85,   86,    1,   85,   86,   44,   85,   86,    2,
       85,   86,   47,   85,   86,    4,   85,   86,   74,   76,
       85,   86,   24,   85,   86,   45,   85,   86,   10,   85,
       86,   25,   85,   86,    9,   85,   86,   46,   85,   86,
       77,   85,   86,   42,   85,   86,   43,   85,   86,   20,
       85,   86,   48,   77,   85,   86,   77,   85,   86,   77,
       85,   86,   77,   85,   86,   77,   85,   86,   77,   85,

       86,   77,   85,   86,   77,   85,   86,   77,   85,   86,
       77,   85,   86,   77,   85,   86,   77,   85,   86,   77,
       85,   86,   77,   85,   86,   77,   85,   86,   40,   85,
       86,   19,   85,   86,   41,   85,   86,   21,   85,   86,
       84,   85,   86,   74,   76,   85,   86,   24,   85,   86,
       45,   85,   86,   10,   85,   86,   25,   85,   86,    9,
       85,   86,   46,   85,   86,   85,   86,   77,   85,   86,
       42,   85,   86,   43,   85,   86,   20,   85,   86,   48,
       77,   85,   86,   77,   85,   86,   77,   85,   86,   77,
       85,   86,   77,   85,   86,   77,   85,   86,   77,   85,

       86,   77,   85,   86,   77,   85,   86,   77,   85,   86,
       77,   85,   86,   77,   85,   86,   77,   85,   86,   77,
       85,   86,   77,   85,   86,   73,   86,   86,   14,   79,
       31,   15,   32,    6,   28,    7,   26,    8,   27,   49,
       76,   81,   30,   75,   74,   76,   22,   12,   13,   11,
       23,   77,   34,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   50,   77,   77,   56,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   33,   16,   78,
       74,   76,   22,   12,   13,   11,   23,   77,   34,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   50,   77,

       77,   56,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   73,   79,   29,   81,   75,   76,   35,
       36,   77,   77,   77,   77,   77,   77,   77,   53,   77,
       77,   77,   67,   77,   77,   63,   77,   64,   77,   70,
       77,   77,   77,   77,   68,   77,   77,   76,   35,   36,
       77,   77,   77,   77,   77,   77,   77,   53,   77,   77,
       77,   77,   67,   77,   77,   63,   77,   64,   77,   70,
       77,   77,   77,   77,   68,   77,   77,   75,   77,   77,
       77,   77,   51,   77,   60,   77,   77,   69,   77,   77,
       55,   77,   77,   77,   65,   77,   77,   77,   77,   77,

       77,   51,   77,   60,   77,   77,   69,   77,   77,   77,
       55,   77,   77,   77,   65,   77,   77,   58,   77,   71,
       77,   77,   61,   77,   66,   77,   77,   77,   77,   52,
       77,   58,   77,   71,   77,   77,   61,   77,   66,   77,
       77,   77,   77,   77,   52,   77,   83,   82,   77,   62,
       77,   57,   77,   54,   77,   77,   62,   77,   77,   57,
       77,   54,   77,   77,   77,   77,   59,   77,   59,   77,
       72
    } ;

static yyconst short int yy_accept[311] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   12,
       14,   17,   20,   23,   25,   28,   31,   34,   37,   40,
       43,   46,   49,   53,   56,   59,   62,   65,   68,   71,
       74,   77,   80,   83,   87,   90,   93,   96,   99,  102,
      105,  108,  111,  114,  117,  120,  123,  126,  129,  132,
      135,  138,  141,  144,  148,  151,  154,  157,  160,  163,
      166,  168,  171,  174,  177,  180,  184,  187,  190,  193,
      196,  199,  202,  205,  208,  211,  214,  217,  220,  223,
      226,  228,  229,  230,  230,  231,  232,  233,  234,  234,
      235,  236,  237,  238,  239,  240,  241,  242,  243,  244,

      245,  247,  247,  248,  249,  250,  251,  252,  253,  254,
      255,  256,  257,  258,  259,  260,  261,  262,  263,  265,
      266,  268,  269,  270,  271,  272,  273,  274,  275,  276,
      277,  278,  279,  280,  280,  280,  281,  283,  283,  283,
      284,  285,  286,  287,  288,  289,  290,  291,  292,  293,
      294,  295,  296,  297,  298,  299,  301,  302,  304,  305,
      306,  307,  308,  309,  310,  311,  312,  313,  314,  315,
      316,  316,  316,  317,  318,  319,  319,  319,  320,  321,
      322,  323,  324,  325,  326,  327,  328,  329,  331,  332,
      333,  335,  336,  338,  340,  342,  343,  344,  345,  347,

      348,  348,  349,  350,  351,  352,  353,  354,  355,  356,
      357,  358,  360,  361,  362,  363,  365,  366,  368,  370,
      372,  373,  374,  375,  377,  378,  378,  378,  378,  378,
      378,  379,  380,  381,  382,  383,  385,  387,  388,  390,
      391,  393,  394,  395,  397,  398,  398,  399,  400,  401,
      402,  404,  406,  407,  409,  410,  411,  413,  414,  415,
      417,  418,  418,  418,  420,  422,  423,  425,  427,  428,
      429,  430,  432,  432,  434,  436,  437,  439,  441,  442,
      443,  444,  445,  447,  448,  449,  450,  452,  454,  456,
      456,  457,  459,  460,  462,  464,  465,  465,  466,  467,

      469,  469,  471,  471,  471,  471,  471,  471,  472,  472
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   26,   26,   26,   27,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   25,   29,   30,   31,   25,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   26,   48,   49,   50,   51,   52,   53,   54,
       26,   26,   55,   56,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    2,    3,    1,    2,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    7,    7,
        7,    7,    8,    7,    7,    6,    6,    7,    7,    7,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[319] =
    {   0,
        0,   58,  115,  119,  498,  499,  499,  499,  475,  491,
      499,  473,  111,  485,  499,  499,  113,  110,  499,  114,
      475,  109,  112,  499,  499,  119,  470,  121,  499,    0,
      499,  499,  469,    0,  442,  103,  453,   91,  115,  113,
      116,  115,  455,  451,  433,  437,  452,  444,  499,  131,
      499,  499,  125,  153,  151,  156,  157,  160,  161,  165,
      172,  187,  182,  183,  197,  217,  434,  148,  445,  149,
      172,  177,  159,  134,  447,  443,  425,  429,  444,  436,
        0,  499,  499,  469,  468,  499,  499,  499,  463,  449,
      499,  499,  499,  499,  499,  499,  207,    0,  499,  208,

      232,  214,  448,  499,  499,  499,  447,    0,  499,  432,
      435,  421,  432,  415,  423,  419,  413,  415,    0,  412,
        0,  408,  411,  403,  412,  413,  403,  412,  400,  402,
      409,  499,  499,  191,  403,  499,  246,  249,  254,  255,
      250,  258,  260,  272,    0,  275,  411,  414,  400,  411,
      394,  402,  398,  392,  394,    0,  391,  403,  386,  389,
      381,  390,  391,  381,  390,  378,  380,  387,    0,  499,
      421,  416,  499,    0,  262,  215,  406,  405,  499,  499,
      390,  372,  370,  368,  382,  367,  367,    0,  381,  368,
        0,  366,    0,    0,    0,  361,  361,  374,    0,  366,

      374,  281,  276,  280,  375,  357,  355,  353,  367,  352,
      352,    0,  366,  353,  355,    0,  350,    0,    0,    0,
      345,  345,  358,    0,  350,  387,  386,  381,  380,  370,
      369,  344,  336,  344,  345,    0,    0,  346,    0,  333,
        0,  332,  345,    0,  342,  334,  334,  326,  334,  335,
        0,    0,  336,    0,  323,  307,    0,  301,  308,    0,
      305,  331,  326,    0,    0,  284,    0,    0,  272,  265,
      270,    0,  257,    0,    0,  262,    0,    0,  255,  269,
      258,  263,    0,  296,  499,  249,    0,    0,    0,  255,
      236,    0,  220,    0,    0,  218,  215,  188,  253,    0,

      258,    0,  283,  290,  197,  180,  168,  499,  499,  311,
      319,  190,  325,  331,  339,  346,  354,  362
    } ;

static yyconst short int yy_def[319] =
    {   0,
      309,  309,  310,  310,  309,  309,  309,  309,  309,  311,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  312,
      309,  309,  309,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  309,  309,
      309,  309,  309,  313,  313,  313,  313,  313,  313,  313,
      313,  314,  313,  313,  313,  314,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
      315,  309,  309,  311,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  316,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  312,  309,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  309,  309,  309,  309,  309,  313,  313,  313,  313,
      313,  313,  313,  313,   66,  313,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,  315,  309,
      317,  318,  309,  316,  309,  309,  309,  309,  309,  309,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      309,  313,  313,  313,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,  317,  317,  318,  309,  309,
      309,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  309,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,  317,  309,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  309,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,  317,  309,  312,  312,  312,  312,  309,
       66,   66,   66,   66,   66,  312,  309,   66,   66,  312,

      309,   66,  309,  313,  309,  309,  309,  309,    0,  309,
      309,  309,  309,  309,  309,  309,  309,  309
    } ;

static yyconst short int yy_nxt[558] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,    6,   30,   30,   31,   32,   33,
       34,   30,   35,   36,   37,   38,   39,   30,   30,   40,
       30,   30,   41,   30,   42,   43,   30,   44,   45,   46,
       30,   47,   48,   30,   49,   50,   51,   52,    6,   53,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   62,   63,   64,   65,   66,   62,
       67,   68,   69,   70,   71,   62,   62,   72,   62,   62,

       73,   62,   74,   75,   62,   76,   77,   78,   62,   79,
       80,   62,   49,   50,   51,   52,   82,   82,   87,   82,
       82,   82,   92,   82,   90,   98,  134,  100,   94,  101,
       99,   93,   88,  114,   91,   95,   96,   82,  102,  103,
      104,   82,  106,  107,  115,  111,  116,  102,  112,  119,
      124,  122,  132,  136,  125,  136,  120,  121,  136,  136,
      117,  123,  136,  136,  135,  118,  309,  136,  100,  161,
      137,  309,  309,  162,  136,  309,  309,  140,  141,  139,
      309,  142,  143,  144,  136,  136,  133,  309,  139,  136,
      148,  151,  134,  149,  159,  108,  308,  309,  309,  136,

      307,  306,  152,  153,  160,  138,  138,  138,  138,  138,
      138,  138,  309,  156,  138,  138,  138,  154,  146,  136,
      157,  158,  155,  302,   97,  175,  177,  230,  177,  230,
      135,  178,  231,  102,  176,  138,  138,  138,  138,  138,
      138,  138,  102,  176,  138,  138,  138,  100,  136,  101,
      301,  136,  136,  300,  303,  299,  136,  136,  102,  303,
      136,  100,  136,  137,  309,  309,  177,  102,  177,  309,
      309,  202,  139,  309,  136,  309,  203,  136,  136,  175,
      304,  139,  136,  136,  303,  305,  298,  309,  176,  297,
      309,  309,  136,  204,  306,  309,  309,  176,  202,  296,

      284,  295,  294,  293,  292,  309,  291,  290,  289,  288,
      305,   81,   81,   81,   81,   81,   81,   81,   81,   84,
       84,  287,   84,   84,   84,   84,   84,  138,  286,  138,
      138,  138,  138,  145,  285,  284,  145,  145,  145,  169,
      283,  282,  169,  169,  169,  169,  174,  174,  281,  174,
      174,  174,  174,  174,  226,  226,  226,  280,  226,  226,
      226,  226,  228,  228,  228,  228,  228,  228,  228,  228,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  231,  231,  263,  229,
      262,  227,  261,  260,  259,  258,  257,  256,  255,  254,

      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  178,  178,  229,  227,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      173,  172,  171,  170,  168,  167,  166,  165,  164,  163,
      150,  147,  131,  130,  129,  128,  127,  126,  113,  110,
      109,  105,   97,   89,   86,   85,   83,  309,    5,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309
    } ;

static yyconst short int yy_chk[558] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    3,    3,   13,    3,
        4,    4,   18,    4,   17,   22,   53,   23,   20,   23,
       22,   18,   13,   38,   17,   20,   20,    3,   23,   26,
       26,    4,   28,   28,   38,   36,   39,   23,   36,   40,
       42,   41,   50,   55,   42,   54,   40,   40,   56,   57,
       39,   41,   58,   59,   53,   39,   55,   60,   54,   74,
       54,   56,   57,   74,   61,   58,   59,   57,   57,   54,
       60,   58,   59,   59,   63,   64,   50,   61,   54,   62,
       68,   70,  134,   68,   73,  312,  307,   63,   64,   65,

      306,  305,   70,   71,   73,   62,   62,   62,   62,   62,
       62,   62,   65,   72,   62,   62,   62,   71,   65,   66,
       72,   72,   71,  298,   97,  100,  102,  176,  102,  176,
      134,  102,  176,   97,  100,   66,   66,   66,   66,   66,
       66,   66,   97,  100,   66,   66,   66,  101,  137,  101,
      297,  138,  141,  296,  299,  293,  139,  140,  101,  301,
      142,  137,  143,  137,  138,  141,  139,  101,  139,  139,
      140,  139,  137,  142,  144,  143,  140,  146,  203,  175,
      299,  137,  204,  202,  303,  301,  291,  144,  175,  290,
      146,  203,  304,  144,  304,  204,  202,  175,  202,  286,

      284,  282,  281,  280,  279,  304,  276,  273,  271,  270,
      303,  310,  310,  310,  310,  310,  310,  310,  310,  311,
      311,  269,  311,  311,  311,  311,  311,  313,  266,  313,
      313,  313,  313,  314,  263,  262,  314,  314,  314,  315,
      261,  259,  315,  315,  315,  315,  316,  316,  258,  316,
      316,  316,  316,  316,  317,  317,  317,  256,  317,  317,
      317,  317,  318,  318,  318,  318,  318,  318,  318,  318,
      255,  253,  250,  249,  248,  247,  246,  245,  243,  242,
      240,  238,  235,  234,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  223,  222,  221,  217,  215,  214,  213,

      211,  210,  209,  208,  207,  206,  205,  201,  200,  198,
      197,  196,  192,  190,  189,  187,  186,  185,  184,  183,
      182,  181,  178,  177,  172,  171,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  135,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  120,  118,
      117,  116,  115,  114,  113,  112,  111,  110,  107,  103,
       90,   89,   85,   84,   80,   79,   78,   77,   76,   75,
       69,   67,   48,   47,   46,   45,   44,   43,   37,   35,
       33,   27,   21,   14,   12,   10,    9,    5,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309
    } ;

#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define INITIAL 0

#include "Exa1Scanner.h"
#include <stdio.h>
#include <stdlib.h>
#include "Spring.h"

int newfile(char * fn);
int popfile();

#define IFILE 1


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
    if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
        YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
    if ( yyleng > 0 ) \
        yy_current_buffer->yy_at_bol = \
                (yytext[yyleng - 1] == '\n'); \
    YY_USER_ACTION

YY_DECL
    {
    register yy_state_type yy_current_state;
    register char *yy_cp, *yy_bp;
    register int yy_act;




    if ( yy_init )
        {
        yy_init = 0;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif

        if ( ! yy_start )
            yy_start = 1;	/* first start state */

        if ( ! yyin )
            yyin = &cin;

        if ( ! yyout )
            yyout = &cout;

        if ( ! yy_current_buffer )
            yy_current_buffer =
                yy_create_buffer( yyin, YY_BUF_SIZE );

        yy_load_buffer_state();
        }

    while ( 1 )		/* loops until end-of-file is reached */
        {
        yy_cp = yy_c_buf_p;

        /* Support of yytext. */
        *yy_cp = yy_hold_char;

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run.
         */
        yy_bp = yy_cp;

        yy_current_state = yy_start;
        yy_current_state += YY_AT_BOL();
        yy_state_ptr = yy_state_buf;
        *yy_state_ptr++ = yy_current_state;
yy_match:
        do
            {
            register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
            while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
                {
                yy_current_state = (int) yy_def[yy_current_state];
                if ( yy_current_state >= 310 )
                    yy_c = yy_meta[(unsigned int) yy_c];
                }
            yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
            *yy_state_ptr++ = yy_current_state;
            ++yy_cp;
            }
        while ( yy_base[yy_current_state] != 499 );

yy_find_action:
        yy_current_state = *--yy_state_ptr;
        yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
        for ( ; ; ) /* until we find what rule we matched */
            {
            if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
                {
                yy_act = yy_acclist[yy_lp];
                    {
                    yy_full_match = yy_cp;
                    break;
                    }
                }
            --yy_cp;
            yy_current_state = *--yy_state_ptr;
            yy_lp = yy_accept[yy_current_state];
            }

        YY_DO_BEFORE_ACTION;

        if ( yy_act != YY_END_OF_BUFFER )
            {
            int yyl;
            for ( yyl = 0; yyl < yyleng; ++yyl )
                if ( yytext[yyl] == '\n' )
                    ++yylineno;
            }

do_action:	/* This label is used only to access EOF actions. */


        switch ( yy_act )
    { /* beginning of action switch */
case 1:
case 2:
case 3:
case 4:
case 5:
YY_RULE_SETUP
{ return yytext[0]; }
    YY_BREAK
case 6:
YY_RULE_SETUP
{ return TOKENS::EXP; }
    YY_BREAK
case 7:
YY_RULE_SETUP
{ return TOKENS::INCREMENT; }
    YY_BREAK
case 8:
YY_RULE_SETUP
{ return TOKENS::DECREMENT; }
    YY_BREAK
case 9:
YY_RULE_SETUP
{ return TOKENS::CMP_G; }
    YY_BREAK
case 10:
YY_RULE_SETUP
{ return TOKENS::CMP_L; }
    YY_BREAK
case 11:
YY_RULE_SETUP
{ return TOKENS::CMP_GE; }
    YY_BREAK
case 12:
YY_RULE_SETUP
{ return TOKENS::CMP_LE; }
    YY_BREAK
case 13:
YY_RULE_SETUP
{ return TOKENS::CMP_E; }
    YY_BREAK
case 14:
YY_RULE_SETUP
{ return TOKENS::CMP_NE; }
    YY_BREAK
case 15:
YY_RULE_SETUP
{ return TOKENS::LOGICAL_AND; }
    YY_BREAK
case 16:
YY_RULE_SETUP
{ return TOKENS::LOGICAL_OR; }
    YY_BREAK
case 17:
YY_RULE_SETUP
{ return TOKENS::LOGICAL_NOT; }
    YY_BREAK
case 18:
YY_RULE_SETUP
{ return TOKENS::BIT_AND; }
    YY_BREAK
case 19:
YY_RULE_SETUP
{ return TOKENS::BIT_OR; }
    YY_BREAK
case 20:
YY_RULE_SETUP
{ return TOKENS::BIT_XOR; }
    YY_BREAK
case 21:
YY_RULE_SETUP
{ return TOKENS::BIT_COM; }
    YY_BREAK
case 22:
YY_RULE_SETUP
{ return TOKENS::BIT_SHIFT_LEFT; }
    YY_BREAK
case 23:
YY_RULE_SETUP
{ return TOKENS::BIT_SHIFT_RIGHT; }
    YY_BREAK
case 24:
YY_RULE_SETUP
{ return ':'; }
    YY_BREAK
case 25:
YY_RULE_SETUP
{ return '='; }
    YY_BREAK
case 26:
YY_RULE_SETUP
{ yylval->m_Int = 219; return TOKENS::COM_ASSIGN; }
    YY_BREAK
case 27:
YY_RULE_SETUP
{ yylval->m_Int = 220; return TOKENS::COM_ASSIGN; }
    YY_BREAK
case 28:
YY_RULE_SETUP
{ yylval->m_Int = 221; return TOKENS::COM_ASSIGN; }
    YY_BREAK
case 29:
YY_RULE_SETUP
{ yylval->m_Int = 222; return TOKENS::COM_ASSIGN; }
    YY_BREAK
case 30:
YY_RULE_SETUP
{ yylval->m_Int = 223; return TOKENS::COM_ASSIGN; }
    YY_BREAK
case 31:
YY_RULE_SETUP
{ yylval->m_Int = 224; return TOKENS::COM_ASSIGN; }
    YY_BREAK
case 32:
YY_RULE_SETUP
{ yylval->m_Int = 225; return TOKENS::COM_ASSIGN; }
    YY_BREAK
case 33:
YY_RULE_SETUP
{ yylval->m_Int = 226; return TOKENS::COM_ASSIGN; }
    YY_BREAK
case 34:
YY_RULE_SETUP
{ yylval->m_Int = 227; return TOKENS::COM_ASSIGN; }
    YY_BREAK
case 35:
YY_RULE_SETUP
{ yylval->m_Int = 228; return TOKENS::COM_ASSIGN; }
    YY_BREAK
case 36:
YY_RULE_SETUP
{ yylval->m_Int = 229; return TOKENS::COM_ASSIGN; }
    YY_BREAK
case 37:
case 38:
case 39:
case 40:
case 41:
case 42:
case 43:
case 44:
case 45:
case 46:
case 47:
case 48:
YY_RULE_SETUP
{ return yytext[0]; }
    YY_BREAK
case 49:
YY_RULE_SETUP
{ return TOKENS::ARROW; }
    YY_BREAK
case 50:
YY_RULE_SETUP
{ return TOKENS::IF; }
    YY_BREAK
case 51:
YY_RULE_SETUP
{ return TOKENS::ELSE; }
    YY_BREAK
case 52:
YY_RULE_SETUP
{ return TOKENS::WHILE; }
    YY_BREAK
case 53:
YY_RULE_SETUP
{ return TOKENS::FOR; }
    YY_BREAK
case 54:
YY_RULE_SETUP
{ return TOKENS::SWITCH; }
    YY_BREAK
case 55:
YY_RULE_SETUP
{ return TOKENS::LOOP; }
    YY_BREAK
case 56:
YY_RULE_SETUP
{ return TOKENS::IN; }
    YY_BREAK
case 57:
YY_RULE_SETUP
{ return TOKENS::RETURN; }
    YY_BREAK
case 58:
YY_RULE_SETUP
{ return TOKENS::BREAK; }
    YY_BREAK
case 59:
YY_RULE_SETUP
{ return TOKENS::CONTINUE; }
    YY_BREAK
case 60:
YY_RULE_SETUP
{ return TOKENS::EXIT; }
    YY_BREAK
case 61:
YY_RULE_SETUP
{return TOKENS::DEBUG; }
    YY_BREAK
case 62:
YY_RULE_SETUP
{return TOKENS::USING; }
    YY_BREAK
case 63:
YY_RULE_SETUP
{return TOKENS::NEW; }
    YY_BREAK
case 64:
YY_RULE_SETUP
{return TOKENS::NIL; }
    YY_BREAK
case 65:
YY_RULE_SETUP
{return TOKENS::TRUE;}
    YY_BREAK
case 66:
YY_RULE_SETUP
{return TOKENS::FALSE;}
    YY_BREAK
case 67:
YY_RULE_SETUP
{return TOKENS::LET; }
    YY_BREAK
case 68:
YY_RULE_SETUP
{return TOKENS::LET; }
    YY_BREAK
case 69:
YY_RULE_SETUP
{return TOKENS::FUNC;}
    YY_BREAK
case 70:
YY_RULE_SETUP
{return TOKENS::OBJECT; }
    YY_BREAK
case 71:
YY_RULE_SETUP
{return TOKENS::OBJECT; }
    YY_BREAK
case 72:
YY_RULE_SETUP
{BEGIN IFILE;}
    YY_BREAK
case 73:
YY_RULE_SETUP
{
                        yylineno++;
                        if(!newfile(yytext)) yyterminate();
                        BEGIN INITIAL;
                    }
    YY_BREAK
case 74:
YY_RULE_SETUP
{
    yylval->m_Int = atoi(yytext);
    return TOKENS::T_INT;}
    YY_BREAK
case 75:
case 76:
YY_RULE_SETUP
{
    yylval->m_Double = atof(yytext);
    return TOKENS::REAL;}
    YY_BREAK
case 77:
YY_RULE_SETUP
{
    int len = strlen(yytext);
    yylval->m_id = (char *)malloc((len+1)*sizeof(char));
    strcpy(yylval->m_id, yytext);
    return TOKENS::ID; }
    YY_BREAK
case 78:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{
    qDebug() <<"发现中文";
}
    YY_BREAK
case 79:
YY_RULE_SETUP
{
    int len = strlen(yytext);
    yylval->m_id = (char *)malloc((len+1)*sizeof(char));
    strcpy(yylval->m_id, yytext);
    return TOKENS::STRING; }
    YY_BREAK
case 80:
YY_RULE_SETUP
{ return TOKENS::EOL;}
    YY_BREAK
case 81:
case 82:
case 83:
case 84:
YY_RULE_SETUP
{ /* ignore white space */ }
    YY_BREAK
case 85:
YY_RULE_SETUP
{/* std::string tip(yytext);
    tip = "Unknown character: " + tip;
//    std::cout << tip.;
//    qDebug()<<QString::fromStdString(tip);
    qDebug()<<QString::fromLocal8Bit(tip.c_str());
/*    if(Spring::springIOHelper != nullptr)
        Spring::springIOHelper->onError(SpringErrorCode::SPRING_ERROR_LEXICAL_ERROR, tip, lineno());

    std::string strStd = "可可西";
    qDebug() << QString::fromLocal8Bit("测试");
    qDebug() << QString::fromLocal8Bit(strStd.c_str()); */

    }
    YY_BREAK
case 86:
YY_RULE_SETUP
YY_FATAL_ERROR( "flex scanner jammed" );
    YY_BREAK
            case YY_STATE_EOF(INITIAL):
            case YY_STATE_EOF(IFILE):
                yyterminate();

    case YY_END_OF_BUFFER:
        {
        /* Amount of text matched not including the EOB char. */
        int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

        /* Undo the effects of YY_DO_BEFORE_ACTION. */
        *yy_cp = yy_hold_char;
        YY_RESTORE_YY_MORE_OFFSET

        if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
            {
            /* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between yy_current_buffer and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.
             */
            yy_n_chars = yy_current_buffer->yy_n_chars;
            yy_current_buffer->yy_input_file = yyin;
            yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
            }

        /* Note that here we test for yy_c_buf_p "<=" to the position
         * of the first EOB in the buffer, since yy_c_buf_p will
         * already have been incremented past the NUL character
         * (since all states make transitions on EOB to the
         * end-of-buffer state).  Contrast this with the test
         * in input().
         */
        if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            { /* This was really a NUL. */
            yy_state_type yy_next_state;

            yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

            yy_current_state = yy_get_previous_state();

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).
             */

            yy_next_state = yy_try_NUL_trans( yy_current_state );

            yy_bp = yytext_ptr + YY_MORE_ADJ;

            if ( yy_next_state )
                {
                /* Consume the NUL. */
                yy_cp = ++yy_c_buf_p;
                yy_current_state = yy_next_state;
                goto yy_match;
                }

            else
                {
                yy_cp = yy_c_buf_p;
                goto yy_find_action;
                }
            }

        else switch ( yy_get_next_buffer() )
            {
            case EOB_ACT_END_OF_FILE:
                {
                yy_did_buffer_switch_on_eof = 0;

                if ( yywrap() )
                    {
                    /* Note: because we've taken care in
                     * yy_get_next_buffer() to have set up
                     * yytext, we can now set up
                     * yy_c_buf_p so that if some total
                     * hoser (like flex itself) wants to
                     * call the scanner after we return the
                     * YY_NULL, it'll still work - another
                     * YY_NULL will get returned.
                     */
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                    }

                else
                    {
                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
                    }
                break;
                }

            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p =
                    yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_match;

            case EOB_ACT_LAST_MATCH:
                yy_c_buf_p =
                &yy_current_buffer->yy_ch_buf[yy_n_chars];

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
        break;
        }

    default:
        YY_FATAL_ERROR(
            "fatal flex scanner internal error--no action found" );
    } /* end of action switch */
        } /* end of scanning one token */
    } /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
    {
    yyin = arg_yyin;
    yyout = arg_yyout;
    yy_c_buf_p = 0;
    yy_init = 1;
    yy_start = 0;
    yy_flex_debug = 0;
    yylineno = 1;	// this will only get updated if %option yylineno

    yy_did_buffer_switch_on_eof = 0;

    yy_looking_for_trail_begin = 0;
    yy_more_flag = 0;
    yy_more_len = 0;
    yy_more_offset = yy_prev_more_offset = 0;

    yy_start_stack_ptr = yy_start_stack_depth = 0;
    yy_start_stack = 0;

    yy_current_buffer = 0;

#ifdef YY_USES_REJECT
    yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
    yy_state_buf = 0;
#endif
    }

yyFlexLexer::~yyFlexLexer()
    {
    delete yy_state_buf;
    yy_delete_buffer( yy_current_buffer );
    }

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
    {
    if ( new_in )
        {
        yy_delete_buffer( yy_current_buffer );
        yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
        }

    if ( new_out )
        yyout = new_out;
    }

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
    {
    if ( yyin->eof() || yyin->fail() )
        return 0;

#ifdef YY_INTERACTIVE
    yyin->get( buf[0] );

    if ( yyin->eof() )
        return 0;

    if ( yyin->bad() )
        return -1;

    return 1;

#else
    (void) yyin->read( buf, max_size );

    if ( yyin->bad() )
        return -1;
    else
        return yyin->gcount();
#endif
    }

void yyFlexLexer::LexerOutput( const char* buf, int size )
    {
    (void) yyout->write( buf, size );
    }

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
    {
    register char *dest = yy_current_buffer->yy_ch_buf;
    register char *source = yytext_ptr;
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
        YY_FATAL_ERROR(
        "fatal flex scanner internal error--end of buffer missed" );

    if ( yy_current_buffer->yy_fill_buffer == 0 )
        { /* Don't try to fill the buffer, so this is an EOF. */
        if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
            {
            /* We matched a single character, the EOB, so
             * treat this as a final EOF.
             */
            return EOB_ACT_END_OF_FILE;
            }

        else
            {
            /* We matched some text prior to the EOB, first
             * process it.
             */
            return EOB_ACT_LAST_MATCH;
            }
        }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

    for ( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
        yy_current_buffer->yy_n_chars = yy_n_chars = 0;

    else
        {
        int num_to_read =
            yy_current_buffer->yy_buf_size - number_to_move - 1;

        while ( num_to_read <= 0 )
            { /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
            YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = yy_current_buffer;

            int yy_c_buf_p_offset =
                (int) (yy_c_buf_p - b->yy_ch_buf);

            if ( b->yy_is_our_buffer )
                {
                int new_size = b->yy_buf_size * 2;

                if ( new_size <= 0 )
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                    yy_flex_realloc( (void *) b->yy_ch_buf,
                             b->yy_buf_size + 2 );
                }
            else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = 0;

            if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR(
                "fatal error - scanner input buffer overflow" );

            yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

            num_to_read = yy_current_buffer->yy_buf_size -
                        number_to_move - 1;
#endif
            }

        if ( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
            yy_n_chars, num_to_read );

        yy_current_buffer->yy_n_chars = yy_n_chars;
        }

    if ( yy_n_chars == 0 )
        {
        if ( number_to_move == YY_MORE_ADJ )
            {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart( yyin );
            }

        else
            {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_buffer_status =
                YY_BUFFER_EOF_PENDING;
            }
        }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

    return ret_val;
    }


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
    {
    register yy_state_type yy_current_state;
    register char *yy_cp;

    yy_current_state = yy_start;
    yy_current_state += YY_AT_BOL();
    yy_state_ptr = yy_state_buf;
    *yy_state_ptr++ = yy_current_state;

    for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
        {
        register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
        while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
            {
            yy_current_state = (int) yy_def[yy_current_state];
            if ( yy_current_state >= 310 )
                yy_c = yy_meta[(unsigned int) yy_c];
            }
        yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
        *yy_state_ptr++ = yy_current_state;
        }

    return yy_current_state;
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
    {
    register int yy_is_jam;

    register YY_CHAR yy_c = 1;
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
        {
        yy_current_state = (int) yy_def[yy_current_state];
        if ( yy_current_state >= 310 )
            yy_c = yy_meta[(unsigned int) yy_c];
        }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
    yy_is_jam = (yy_current_state == 309);
    if ( ! yy_is_jam )
        *yy_state_ptr++ = yy_current_state;

    return yy_is_jam ? 0 : yy_current_state;
    }


void yyFlexLexer::yyunput( int c, register char* yy_bp )
    {
    register char *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
        { /* need to shift things up to make room */
        /* +2 for EOB chars. */
        register int number_to_move = yy_n_chars + 2;
        register char *dest = &yy_current_buffer->yy_ch_buf[
                    yy_current_buffer->yy_buf_size + 2];
        register char *source =
                &yy_current_buffer->yy_ch_buf[number_to_move];

        while ( source > yy_current_buffer->yy_ch_buf )
            *--dest = *--source;

        yy_cp += (int) (dest - source);
        yy_bp += (int) (dest - source);
        yy_current_buffer->yy_n_chars =
            yy_n_chars = yy_current_buffer->yy_buf_size;

        if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
            YY_FATAL_ERROR( "flex scanner push-back overflow" );
        }

    *--yy_cp = (char) c;

    if ( c == '\n' )
        --yylineno;

    yytext_ptr = yy_bp;
    yy_hold_char = *yy_cp;
    yy_c_buf_p = yy_cp;
    }


int yyFlexLexer::yyinput()
    {
    int c;

    *yy_c_buf_p = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
        {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
        if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            /* This was really a NUL. */
            *yy_c_buf_p = '\0';

        else
            { /* need more input */
            int offset = yy_c_buf_p - yytext_ptr;
            ++yy_c_buf_p;

            switch ( yy_get_next_buffer() )
                {
                case EOB_ACT_LAST_MATCH:
                    /* This happens because yy_g_n_b()
                     * sees that we've accumulated a
                     * token and flags that we need to
                     * try matching the token before
                     * proceeding.  But for input(),
                     * there's no matching to consider.
                     * So convert the EOB_ACT_LAST_MATCH
                     * to EOB_ACT_END_OF_FILE.
                     */

                    /* Reset buffer status. */
                    yyrestart( yyin );

                    /* fall through */

                case EOB_ACT_END_OF_FILE:
                    {
                    if ( yywrap() )
                        return EOF;

                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
#ifdef __cplusplus
                    return yyinput();
#else
                    return input();
#endif
                    }

                case EOB_ACT_CONTINUE_SCAN:
                    yy_c_buf_p = yytext_ptr + offset;
                    break;
                }
            }
        }

    c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
    *yy_c_buf_p = '\0';	/* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;

    yy_current_buffer->yy_at_bol = (c == '\n');
    if ( yy_current_buffer->yy_at_bol )
        ++yylineno;

    return c;
    }


void yyFlexLexer::yyrestart( istream* input_file )
    {
    if ( ! yy_current_buffer )
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
    {
    if ( yy_current_buffer == new_buffer )
        return;

    if ( yy_current_buffer )
        {
        /* Flush out information for old buffer. */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
        }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


void yyFlexLexer::yy_load_buffer_state()
    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
    if ( ! b->yy_ch_buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_is_our_buffer = 1;

    yy_init_buffer( b, file );

    return b;
    }


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
    {
    if ( ! b )
        return;

    if ( b == yy_current_buffer )
        yy_current_buffer = (YY_BUFFER_STATE) 0;

    if ( b->yy_is_our_buffer )
        yy_flex_free( (void *) b->yy_ch_buf );

    yy_flex_free( (void *) b );
    }


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

    {
    yy_flush_buffer( b );

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

    b->yy_is_interactive = 0;
    }


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
    {
    if ( ! b )
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if ( b == yy_current_buffer )
        yy_load_buffer_state();
    }


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
    {
    if ( yy_start_stack_ptr >= yy_start_stack_depth )
        {
        yy_size_t new_size;

        yy_start_stack_depth += YY_START_STACK_INCR;
        new_size = yy_start_stack_depth * sizeof( int );

        if ( ! yy_start_stack )
            yy_start_stack = (int *) yy_flex_alloc( new_size );

        else
            yy_start_stack = (int *) yy_flex_realloc(
                    (void *) yy_start_stack, new_size );

        if ( ! yy_start_stack )
            YY_FATAL_ERROR(
            "out of memory expanding start-condition stack" );
        }

    yy_start_stack[yy_start_stack_ptr++] = YY_START;

    BEGIN(new_state);
    }
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
    {
    if ( --yy_start_stack_ptr < 0 )
        YY_FATAL_ERROR( "start-condition stack underflow" );

    BEGIN(yy_start_stack[yy_start_stack_ptr]);
    }
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
    {
    return yy_start_stack[yy_start_stack_ptr - 1];
    }
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
    {
    cerr << msg << '\n';
    exit( YY_EXIT_FAILURE );
    }


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        yytext[yyleng] = yy_hold_char; \
        yy_c_buf_p = yytext + n; \
        yy_hold_char = *yy_c_buf_p; \
        *yy_c_buf_p = '\0'; \
        yyleng = n; \
        } \
    while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
    {
    register int i;
    for ( i = 0; i < n; ++i )
        s1[i] = s2[i];
    }
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
    {
    register int n;
    for ( n = 0; s[n]; ++n )
        ;

    return n;
    }
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
    {
    return (void *) malloc( size );
    }

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
    {
    /* The cast to (char *) in the following accommodates both
     * implementations that use char* generic pointers, and those
     * that use void* generic pointers.  It works with the latter
     * because both ANSI C and C++ allow castless assignment from
     * any pointer type to void*, and deal with argument conversions
     * as though doing an assignment.
     */
    return (void *) realloc( (char *) ptr, size );
    }

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
    {
    free( ptr );
    }

#if YY_MAIN
int main()
    {
    yylex();
    return 0;
    }
#endif

/*由于我们在Exa1Scanner.h中重新定义了YYDDECL，因此在此处必须对Exa1FlexLexer::yylex()给予定义*/
int Exa1FlexLexer::yylex()
{
    std::cout << "can not use Exa1FlexLexer::yylex()" << std::endl;
    return 0;
}

int newfile(char * fn)
{
    std::cout << fn << std::endl;
    return 0;
}

int popfile()
{
    std::cout << "popfile" << std::endl;
    return 0;
}
